POST http://localhost/api/v1/compress
Content-Type: application/json

{
    "file": ".testdata/archive/archive.zip",
    "dir": ".testdata/src",
    "filter": ""
}

###

POST  http://localhost/api/v1/extract
Content-Type: application/json

{
    "file": ".testdata/archive/archive.zip",
    "dir": ".testdata/dst/one",
    "filter": ""
}
